### PR TITLE
Supported hundreds of nested HTML

### LINKED ISSUE #201: Can not load hundreds of nested HTML
I can not load hundreds of nested HTML by HTML Purifier.

e.g.
```
<html>
<body>
<div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div>
Can display
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
</div>
</body>
</html>
```

I think that it is caused by the absence of the [LIBXML_PARSEHUGE](http://php.net/manual/en/libxml.constants.php) option in the following processing.
https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Lexer/DOMLex.php#L72

Why are options not specified?
\# I could not find any adverse effects when specifying options...

### PR DESCRIPTION
**Pull request by msuzuki55**
Fixed #201

I am worried about the following.
- Whether to make this change in [config](http://htmlpurifier.org/live/configdoc/plain.html).
  \# Because there was no reason, I do not deal with it, please let me hear your opinion.
- Is the location of my test code correct?

### CODE REVIEW

**Comment by tgalopin** [comment]
I think this should not be merged, IMO it's a source of DoS attacks by providing a large number of nested tags in any form of a website.

**Comment by msuzuki55** [comment]
@tgalopin 
Thank you for your reply.

> IMO it's a source of DoS attacks by providing a large number of nested tags in any form of a website.

Indeed, I agree to you.
However there are cases where I want to enable options.
I want to return the input HTML without unnecessarily cutting it.

How about a design to switch in the config file?
e.g. 
```
  $options = 0;
  if (defined('LIBXML_PARSEHUGE') && $config->get('Core.MitigateParserRestriction')) {
    $options |= LIBXML_PARSEHUGE;
  }

  set_error_handler(array($this, 'muteErrorHandler'));
  $doc->loadHTML($html, $options);
  restore_error_handler();
```

**Comment by tgalopin** [comment]
That seems much better indeed :) . If it's opt-in, security is enabled by default. We should still be careful in the documentation to explain clearly the consequences of this config key.

**Comment by msuzuki55** [comment]
@tgalopin 
Thank you. I fixed it.
https://github.com/ezyang/htmlpurifier/pull/202/commits/aecc088dade5502fe00944f861101d10a22e75c0

**Comment by msuzuki55** [comment]
@tgalopin @ezyang 
Could you confirm this?

**Pull request merged**
