### PR TITLE
Issue 238 remove leading zeroes except if there is only zero

### PR DESCRIPTION
**Pull request by lubomirbartos**
After this change, it trims leading zeros, but leaves the last zero if it is the only number.

### CODE REVIEW

**Comment by lubomirbartos** [comment]
Some tests failed on CI, I fixed it according to the new trimming, is that enough or would you like test explicitly for this trimming?

**Comment by ezyang** [comment]
Nope LGTM

**Comment by lubomirbartos** [comment]
Do you know when will be next release?

**Comment by ezyang** [comment]
Probably not for a bit; maybe we can do a quick point release before the new years...

**Comment by lubomirbartos** [comment]
I would really help us if we could get a tag with this fix.

**Comment by lubomirbartos** [comment]
Hi @ezyang, could I get some stimate of a date of new release? Our customers would like to know when we fix this bug.
Thank you.

**Pull request merged**
