### PR TITLE
Add support for PHP 7.4

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
Strange: all tests pass, but in my project I get error. Missing test case?

```
Array and string offset access syntax with curly braces is deprecated

/var/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Encoder.php:162
/var/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php:177
...
```

**Comment by snapshotpl** [comment]
I see it's fixed in master. Great. Anyway, test for 7.4 are ok :-)

**Comment by snapshotpl** [comment]
@ezyang is it possible to release this changes?

**Comment by emodric** [comment]
@ezyang Hi. I'd also like to see a new release with PHP 7.4 support.

PHP 7.4 is in RC phase and we would like for our builds to be green.

**Comment by ezyang** [comment]
okey maybe this weekend

**Comment by emodric** [comment]
Hi @ezyang. Any news on the release?

**Comment by sebastiaanluca** [comment]
PHP 7.4 has been released, any news on releasing support for it? Currently can't upgrade our app. Thanks!

**Comment by ezyang** [comment]
Yes, 4.12.0 is released and has the compat changes.

**Pull request merged**
