### PR TITLE
fix: CSSTidy ImportantComments not handled properly

### PR DESCRIPTION
**Pull request by Wolfrank1149**
Fix for issue https://github.com/ezyang/htmlpurifier/issues/357

Added a check if `$decls` is an array before the `foreach` and not keeping the value if it's not.

Also added a unit test for that case.

### CODE REVIEW

**Comment by Wolfrank1149** [comment]
The validation is still done, I only skip it for the important comments. Do want me to also check them? If yes, do I validate them like a style or do you have a specifict validation for comments?

**Comment by ezyang** [comment]
Hmm, ok, so basically it sounds like what you are saying is the decls are string, they are comments? I think I would still feel more comfortable if we limit the valid contents of the comment. Can we allow only !important for your use case?

**Review by ezyang — APPROVED** [review]
thank you much appreciated

**Comment by ezyang** [comment]
Woops our ci is broken

**Comment by Monalmos** [comment]
> Fix for issue https://github.com/ezyang/htmlpurifier/issues/357
> 
> 
> 
> Added a check if `$decls` is an array before the `foreach` and not keeping the value if it's not.
> 
> 
> 
> Also added a unit test for that case.

**Comment by Monalmos** [comment]
> You are bypassing validation of style entirely, therefore introducing a security vulnerability here. You must still validate style.

**Pull request merged**
