### PR TITLE
Implement HTML.Noreferrer.

### PR DESCRIPTION
**Pull request by cameron1729**
Hey,

I have implemented a simple Noreferrer module similar to Nofollow. It adds `rel="noreferrer"` to `a` tags when a `target="_blank"` attribute is present. This is useful because it is possible to use JavaScript to modify the original tab/window in the newly opened tab/window with `window.opener.location.replace(...` which can be a potential security risk. It would be nice to see this in an official release.

If you need anything please let me know :]

### CODE REVIEW

**Comment by markn86** [comment]
+1 to get this upstream.

**Comment by ezyang** [comment]
Hello, thanks for the patch. Do you think that noreferrer should be enabled by default with %HTML.TargetBlank? I think it should be!

**Comment by ezyang** [comment]
I changed the behavior a bit and merged.

**Comment by cameron1729** [comment]
Thanks!

**Comment by markn86** [comment]
CAM BALL!

**Pull request closed without merging**
