### PR TITLE
Fixed Issue #264: <thead> element removed from <table>

### PR DESCRIPTION
**Pull request by marartner**
…if there are no `<tbody>` or `<tr>` elements

### CODE REVIEW

**Comment by ezyang** [comment]
Can you add a test for this behavior?

**Comment by marartner** [comment]
I added tests, but I can't confirm if they work since I failed getting the testrunner to work on my machine and don't have the time right now to investigate further. Here's the error I get on running it (on `master` without any changes)

```sh
$ php tests/index.php

Fatal error: Abstract function HTMLPurifier_AttrDefTestable::validate() cannot contain body in /Users/marartner/code/simpletest/src/mock_objects.php(1417) : eval()'d code on line 138

Call Stack:
    0.0015     487536   1. {main}() /Users/marartner/code/htmlpurifier/tests/index.php:0
    0.0836    6114720   2. htmlpurifier_add_test() /Users/marartner/code/htmlpurifier/tests/index.php:212
    0.0838    6122392   3. require_once('/Users/marartner/code/htmlpurifier/tests/HTMLPurifier/AttrDefTest.php') /Users/marartner/code/htmlpurifier/tests/common.php:166
    0.0838    6122392   4. Mock::generatePartial() /Users/marartner/code/htmlpurifier/tests/HTMLPurifier/AttrDefTest.php:6
    0.0839    6122576   5. MockGenerator->generatePartial() /Users/marartner/code/simpletest/src/mock_objects.php:1293
```

**Comment by marartner** [comment]
```
$ php tests/index.php

All HTML Purifier tests on PHP 7.4.10
OK
Test cases run: 220/220, Passes: 2778, Failures: 0, Exceptions: 0```

**Review by ezyang — APPROVED** [review]

**Comment by marartner** [comment]
Might I bother you to publish a new release with this and other fixes that were merged since the last one?

**Pull request merged**
