### PR TITLE
Remove BOM from file INSTALL.fr.utf8

### PR DESCRIPTION
**Pull request by r-kovalenko**
It's only one file with BOM among project

### CODE REVIEW

**Comment by r-kovalenko** [comment]
https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by ezyang** [comment]
Hm, I /specifically/ put a BOM in that file, because it's the non-ASCII UTF-8 encoded file we have. Is there a reason it's causing a problem?

**Comment by r-kovalenko** [comment]
It's not so big problem. But in our project we are cheking all files and included libraries for the BOM. I decided to remove it, if it is not needed

**Comment by ezyang** [comment]
Merged.

**Pull request closed without merging**
