### PR TITLE
Adds PHP 7.3 to Travis

### PR DESCRIPTION
**Pull request by lksnmnn**
I am currently reviewing our dependencies for PHP 7.3 compatibility.
This should run the the tests on 7.3 :)

### CODE REVIEW

**Comment by lksnmnn** [comment]
I may be able to spend some time on investigating why the tests fail on PHP 7.3.2 on Travis.

**Comment by ThHareau** [comment]
Hello, I just run into the same issue, I fixed it here https://github.com/ProtonMail/htmlpurifier/commit/0d22798921503e082d6dca70471d94ea9a5a955a

In `library/HTMLPurifier/Language/messages/en-x-test.php` and `library/HTMLPurifier/Language/messages/en-x-testmini.php`, you should add a new variable `$errorNames = array();`.

You may also want to change the version of simpletest from `1.1` to `dev-master#72de02a7b80c6bb8864ef9bf66d41d2f58f826bd`.
In 1.1, the mocking is done using old style constructors, which throws a notice in _at least_ php 7.3.4.

**Comment by lksnmnn** [comment]
I added the fixes you've done on your fork :) Thanks!

**Comment by ezyang** [comment]
Yeah, let's just rely on the SimpleTest fork.

**Pull request merged**
