### PR TITLE
Updated translation of installing in french

### PR DESCRIPTION
**Pull request by anthonybocci**
The text was wrong, now it's fixed, translated to french

### CODE REVIEW

**Comment by ezyang** [comment]
Thank, I made some corrections and merged it!

**Comment by anthonybocci** [comment]
There was some garbages ? Sorry !
Happy to helped you !

**Comment by ezyang** [comment]
One typo (s/tity/tidy/), but otherwise, just whitespace cleanup. Thanks for the patch!

**Comment by anthonybocci** [comment]
Ah ok, fine.
Your welcome, if I've any time maybe I come back participate again !
See you

**Comment by anthonybocci** [comment]
I just saw I've forgotten a character,

There is "2.    Include la librairie", But the right word is "Inclure", not "Include". Sorry.
Do you want a new pull request, or not ?

**Comment by ezyang** [comment]
Don't worry, I just went ahead and fixed it.

**Comment by anthonybocci** [comment]
Perfect, thank you !

**Pull request closed without merging**
