### PR TITLE
Support for border radius addeed to CSSDefinition

### PR DESCRIPTION
**Pull request by mattiaswelander**
Support for border radius addeed to CSSDefinition

### CODE REVIEW

**Comment by Daijobou** [comment]
I have include the code in 4.7.0 and try it, but its not working. I found out, I must clear the folder htmlpurifier-4.7.0\library\HTMLPurifier\DefinitionCache\Serializer\CSS\ to take affect this code.

Code working now fine, please add it for next update. ;)

**Comment by ezyang** [comment]
I reimplemented this.

**Comment by teells** [comment]
Using v4.8, this still strips out border-radius. I've cleared the cache file just in case. I also searched the cache file and border-radius wasn't present. (don't know if it should be or not)

**Comment by ezyang** [comment]
You have to turn on a config option to get it. `%CSS.AllowProprietary`

**Pull request closed without merging**
