### PR TITLE
feat: add semantic release

### LINKED ISSUE #304: Is a new release planned?
Hi. I'm currently trying to use htmlpurifier with PHP 8 and I am getting the following syntax error:

```
Parse error: ./vendor/ezyang/htmlpurifier/library/HTMLPurifier.autoload-legacy.php:10
     8|  */
     9| 
  > 10| function __autoload($class)
    11| {
    12|     return HTMLPurifier_Bootstrap::autoload($class);
```

As I can see this issue was fixed in https://github.com/ezyang/htmlpurifier/commit/4285590c90a1eaf36eb6ae147cc1cbfa7aa546a6#diff-b612c84ece435337010ca64e81530a73be5f6109399945520676881e90e56f74. Unfortunately the latest release from 29 Jun 2020 does not contain this fix.

Would it be possible to release a new version that makes it compatible with PHP 8? Are there any blockers?

### PR DESCRIPTION
**Pull request by bytestream**
Requires a GitHub auth token adding to the repository secrets of name `GITHUB_TOKEN` https://docs.github.com/en/actions/security-guides/encrypted-secrets

How does it work? https://semantic-release.gitbook.io/semantic-release/#how-does-it-work

Release notes / change log is generated based on `fix:` / `feat:` commit messages. So the first automatic release won't include historic commits which don't match that format.
* `NEWS` is generated automatically per above using markdown format, so will not look the same as before...
* `WHATSNEW` has been removed as it's difficult to automatically generate

Closes #304

### CODE REVIEW

**Comment by ezyang** [comment]
> So the first automatic release won't include historic commits which don't match that format.

Should do a normal release then before turning this on.

**Comment by ezyang** [comment]
Will need to setup commitizen/commitlint before landing this to ensure commit messages are valid

**Comment by ezyang** [comment]
Wondering if we actually want a release every time a PR is merged. Might be better to offer a stable branch (periodic release) and a dev branch (tracking master)

**Comment by bytestream** [comment]
> Should do a normal release then before turning this on.

Yeah. I can send a PR with the file updates for the release if you want?

> Will need to setup commitizen/commitlint

There's a few GitHub actions that handle stuff like this. I prefer to enforce squashing and lint the PR title. Thoughts - lint PR title, or all commits? 

> Might be better to offer a stable branch (periodic release) and a dev branch (tracking master)

Releasing after every PR seems to be common in JS libraries. It's up to you, but a periodic release would probably require manual action again

**Comment by ezyang** [comment]
> Yeah. I can send a PR with the file updates for the release if you want?

I just cut 4.14.0 so I think we're clear here.

> There's a few GitHub actions that handle stuff like this. I prefer to enforce squashing and lint the PR title. Thoughts - lint PR title, or all commits?

I set the repo to squash by default so we just have to lint PR title.

> Releasing after every PR seems to be common in JS libraries. It's up to you, but a periodic release would probably require manual action again

OK, maybe this is me not understanding semantic release, but what's the point of releases if you release every PR. That seems like what a nightly is for.

**Comment by bytestream** [comment]
> I set the repo to squash by default so we just have to lint PR title.

I'll look at adding a GitHub Action which lints the PR title.

> OK, maybe this is me not understanding semantic release, but what's the point of releases if you release every PR. That seems like what a nightly is for.

It wouldn't necessarily be a point release - `feat:` for minor release, and `fix:` for patch release. 

I think the only real benefit to releasing after every PR is that it's fully automated. The other benefit is that easy to rollback to a previously working version if one PR breaks something.

> Might be better to offer a stable branch (periodic release) and a dev branch (tracking master)

This should be do-able, but would require you to manually merge `dev` into `stable` to trigger a release. I'm not sure there's any specific benefit to that flow.

We could perhaps just make `semantic-release` a manual GitHub Action that only runs on the `master` branch?

**Comment by ezyang** [comment]
I'm down to try with a manual GitHub action to start, and then upgrade into continuous if we like it.

**Comment by bytestream** [comment]
I've updated it so the PR title is linted, and it runs manually.

Two things to note, but I don't think you need to worry about either:
* If using protected branches, replace `GITHUB_TOKEN` with a [Personal Access Token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).
* Configure the repository to [use the squash & merge strategy](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) and tick the option "Default to PR title for squash merge commits".

To manually run the action see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by ezyang** [comment]
I plan to merge this after the upcoming release, then do a "stutter" relase to check that this is working

**Pull request merged**
