### PR TITLE
Replace curly braces with square brackets in string offsets

### LINKED ISSUE #223: PHP 7.4: Array and string offset access syntax with curly braces is deprecated
On PHP 7.4, using HTMLPurifier results in deprecation notices from the title.

This comes for example from this syntax usage: https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/TagTransform/Font.php#L78

### PR DESCRIPTION
**Pull request by emodric**
Fixes #223

### CODE REVIEW

**Comment by emodric** [comment]
Hi! Thanks for the merge! When do you think you could release a patch version with this fix?

**Comment by ezyang** [comment]
Probably not in the near future, unless you convince me it is very urgent.

**Comment by emodric** [comment]
It's not urgent, no, until PHP 7.4 is stable. It would be nice to have our builds green, but I'm not gonna nitpick :)

**Comment by binarious** [comment]
>  unless you convince me it is very urgent

We need to check whether our applications are php 7.4 compatible as early as possible. Htmlpurifier makes it hard for us, because of the deprecations.

**Comment by ezyang** [comment]
You should try testing off of master. It will probably not change much between now and next release

**Comment by fisharebest** [comment]
7.4-rc1 has been released.

It is now time to tag a new version?

**Comment by connorshea** [comment]
PHP 7.4.0-rc4 is coming out tomorrow. A new release of HTMLPurifier would be greatly appreciated :)

**Comment by emodric** [comment]
@ezyang PHP 7.4 is nearing a final release. Can you at least release a patch release to 4.11 ?

**Comment by binarious** [comment]
[v4.12.0](https://github.com/ezyang/htmlpurifier/releases/tag/v4.12.0) has been released which includes this fix.

**Comment by connorshea** [comment]
Thanks!

**Comment by bin20060407** [comment]
PHP 7.4 has been released for a long time, why is this pull not merged?

**Pull request merged**
