### PR TITLE
Add css support for text-decoration-line

### PR DESCRIPTION
**Pull request by lukeluluke**

### CODE REVIEW

**Comment by Rah1x** [comment]
@ezyang 
Do you mean the following?

```
$this->info['text-decoration-line'] = new HTMLPurifier_AttrDef_Enum(
    ['none', 'underline', 'overline', 'line-through']
);
```

**Comment by ezyang** [comment]
Yup plz do

**Comment by Rah1x** [comment]
Done. have a look:
https://github.com/ezyang/htmlpurifier/pull/360

**Comment by Rah1x** [comment]
since this is now completed via https://github.com/ezyang/htmlpurifier/pull/360, we can delete this PR.

**Pull request closed without merging**
