### PR TITLE
Implement tel URI scheme

### PR DESCRIPTION
**Pull request by WesCossick**
This PR adds support for the `tel:` URI scheme. While there are a few caveats, I believe having this support is better than no support at all.

The biggest caveat, which shouldn't be too much of an issue, is that it cleanses the URI to only include the plus sign (if it's in the first character position), digits, and the letter 'x' (capital X's are converted to lowercase x's). I've created an example of what it'll filter here: http://www.regexr.com/3dlqi.

I've been using this filtering for several months now in some production software used globally by a large number of people, and I've found it works very well. Because it simplifies the phone number down to those characters, it supports nearly every type of international phone number, regardless of original formatting. We can also be confident that no malicious code will slip through.

Another caveat is that it does not validate the phone number. This is basically impossible, though. There are just too many ways to format a phone number. You can format them nationally, internationally, and using all sorts of characters and extensions. Phone numbers can also be really short (i.e. `911`) or really long (i.e. `+1 (555) 555-5555; extension=123456789`). The only way I could foresee validation being possible is by building and constantly maintaining a large library of code to handle it, similar to Google's [libphonenumber](https://github.com/googlei18n/libphonenumber).

I added as many tests as I could, and I believe I implemented everything correctly. I had trouble testing it, however, since I'm using PHP 7 and I don't have Net_IDNA2. Please let me know if there's anything I need to add, or if some of the tests fail.

### CODE REVIEW

**Comment by WesCossick** [comment]
Can this be merged in?

**Comment by ezyang** [comment]
Sorry about the delay. The `tel` specification in the RFC is considerably more complex than the regex in this patch. Are we sure we aren't excluding useful phone numbers with the current regex?

**Comment by WesCossick** [comment]
My first comment above explains more details about how it works, but virtually no phone number would be excluded. This is because it simplifies the phone numbers down to a handful of allowed characters. You can see this demonstrated here: http://www.regexr.com/3dlqi.

Unfortunately it's essentially impossible to create regex that could validate every phone number according to the RFC. The only other alternative would be to have no filtering at all.

This will allow essentially 100% of all real phone numbers through. Right now, no phone numbers are being permitted by HTML Purifier.

**Comment by ezyang** [comment]
I squashed, made some minor edits, and pushed.

**Pull request closed without merging**
