### PR TITLE
Add PHP 8.2 to CI

### PR DESCRIPTION
**Pull request by TimWolla**
see ezyang/htmlpurifier#334

### CODE REVIEW

**Comment by ezyang** [comment]
but it fails 👀

**Comment by TimWolla** [comment]
Indeed it does, I trusted #334 and wanted to get the CI in before the release. Maybe someone (@bytestream?) can pick up the last three issues. I won't want time for that on short notice.

**Comment by bytestream** [comment]
@TimWolla https://github.com/ezyang/htmlpurifier/pull/337 :man_shrugging:

**Comment by TimWolla** [comment]
> man_shrugging

Thanks for tackling this!

> PR description should also say

No, because this PR does not actually perform the release as requested in the issue.

**Review by bytestream — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Pull request merged**
