### PR TITLE
Fix: using null instead of false. Fixed CPU is 100% on PHP 7.1.*

### PR DESCRIPTION
**Pull request by Xiphin**

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks for the fix @Xiphin. Just to be clear, BOTH fixes are necessary to prevent the infinite loop? (I would have thought stdClass would be more risky than having current_li set to false: PHP looping on current_li sounds like a honking big bug in PHP!)

**Comment by Xiphin** [comment]
@ezyang using null instead of false is necessary to fix it. the bug is caused by forcing convert type.

**Comment by ezyang** [comment]
So, just to make sure, the renaming of stdClass is cosmetic? 

In any case, thanks for submitting this fix. It would be a great service to PHP if you could boil this down to a minimal repro and post it to https://bugs.php.net/bug.php?id=74623; I am sure the PHP devs will fix this in PHP as well.

**Comment by trsteel88** [comment]
Can we get this tagged please @ezyang

**Comment by trsteel88** [comment]
@ezyang packagist hasn't indexed the latest tag. Are you able to execute a re-crawl?

https://packagist.org/packages/ezyang/htmlpurifier

**Comment by Xiphin** [comment]
@ezyang Suggestion: Enabling the Packagist service hook on your github "settings > Integrations & services >Services" ensures that your package will always be updated instantly when you push to GitHub. 
https://packagist.org/about#how-to-update-packages

**Comment by 0xPaul** [comment]
This still appears to be untagged. Can we get a tag for this fix please?

**Comment by Xiphin** [comment]
@0xPaul 
If you want to use the purifer, you can temporarily use
https://github.com/xlstudio/purifier or
https://packagist.org/packages/xlstudio/purifier
in place of
https://github.com/mewebstudio/Purifier

PS: ezyang/htmlpurifier v4.9.3 is release. You can get it in
https://github.com/ezyang/htmlpurifier/releases/tag/v4.9.3 or
https://packagist.org/packages/ezyang/htmlpurifier

**Pull request merged**
